# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  services.btrfs.autoScrub = {
    enable = true;
    interval = "weekly";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/052ebb9a-e75a-49df-b0be-957e671e0bb1";
    fsType = "btrfs";
    options = ["subvol=@" "noatime" "compress=zstd:3"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/AB1B-DED2";
    fsType = "vfat";
    options = ["defaults" "noatime" "fmask=077" "dmask=0077"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/052ebb9a-e75a-49df-b0be-957e671e0bb1";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/052ebb9a-e75a-49df-b0be-957e671e0bb1";
    fsType = "btrfs";
    options = ["subvol=@nix" "noatime"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/052ebb9a-e75a-49df-b0be-957e671e0bb1";
    fsType = "btrfs";
    options = ["subvol=@log" "noatime"];
  };

  fileSystems."/misc" = {
    device = "/dev/disk/by-uuid/ba45aff9-ea34-481e-97e8-9714b23e89e8";
    fsType = "btrfs";
    options = ["noatime"];
  };

  fileSystems."/hdd" = {
    device = "/dev/disk/by-uuid/807a62c6-58b5-4b0f-97a4-319d4997c8e7";
    fsType = "ext4";
    options = ["defaults" "noatime"];
  };

  boot.tmp.useTmpfs = true;

  swapDevices = [
    {device = "/dev/disk/by-uuid/d36918ed-d475-495b-8765-938a64f61b33";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
